name: Main
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev
    - name: Test
      run: pipenv run test
    - name: Build without fetching GitHub Issues
      run: |
        export DISABLE_GITHUB_ISSUES_FETCH=true
        pipenv run build
      if: ${{ github.event_name == 'pull_request' }}
    - name: Build with fetching GitHub Issues
      run: pipenv run build
      if: ${{ github.event_name != 'pull_request' }}
    - name: Deploy
      run: pipenv run deploy
      if: ${{ github.ref == 'refs/heads/master' }}
